{% set pkgname = "hypothesis" %}
{% set version = "3.52.0" %}
{% set sha256 = "282fcd32100726f588ed98f46721c42ce440960df464d71f331297e8ae67a43c" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - attrs
    - coverage
    - enum34  # [py<34]

{% set pytestcmd = "python -m pytest " %}  
{% set pytestcmd = "python -m pytest -n 0 " %}  # [py35]

test:
  requires:
    - pytest-xdist
    - numpy
    - pandas
    - pytz
    - faker
    - mock
    - flaky
    - ipaddress  # [py2k]
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.strategies
    - hypothesis.stateful
  commands:
    - git clone https://github.com/HypothesisWorks/hypothesis-python.git src
    - cd src
    - {{ pytestcmd }} tests/cover
    - {{ pytestcmd }} tests/datetime
    - {{ pytestcmd }} tests/fakefactory
    - {{ pytestcmd }} tests/numpy
    - {{ pytestcmd }} tests/pandas
    - {{ pytestcmd }} tests/py2  # [py2k]
    - {{ pytestcmd }} tests/py3  # [py3k]
    - {{ pytestcmd }} tests/pytest -p pytester --runpytest subprocess

about:
  home: http://hypothesis.works
  license: MPL 2.0
  license_family: Other
  summary: 'A library for property based testing'
  description: |
      Hypothesis is an advanced testing library for Python. It lets you write
      tests which are parametrized by a source of examples, and then generates
      simple and comprehensible examples that make your tests fail. This lets
      you find more bugs in your code with less work.
  dev_url: https://github.com/HypothesisWorks/hypothesis-python
  doc_url: https://hypothesis.readthedocs.io/

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
