{% set name = "hypothesis" %}
{% set version = "6.111.0" %}

package:
  name: hypothesis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04d0703621d9fdd61c079a4dda07babbe7ebf6d34eee6ad9484a2af0ee721801

build:
  number: 0
  skip: true # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - hypothesis = hypothesis.extra.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - attrs >=22.2.0
    - exceptiongroup  >=1.0.0  # [py<311]
    - sortedcontainers >=2.1.0,<3.0.0
    # Optional, but nice to have for the CLI tool
    - click >=7.0
    - black >=19.10b0
    - rich >=9.0.0
  run_constrained:
    # codemods
    - libcst >=0.3.16
    # pytz
    - pytz >=2014.1
    #dateutil
    - python-dateutil >=1.4
    #lark
    - lark >=0.10.1
    #numpy
    - numpy >=1.17.3
    #pandas
    - pandas >=1.1
    #pytest
    - pytest >=4.6
    #dpcontracts
    #- dpcontracts >=0.4 #Not available currently
    #redis
    - redis-py >=3.0.0
    #django
    - django >=3.2
    # zoneinfo
    - tzdata >=2024a  # [win]
    - backports.zoneinfo >=0.2.1  # [py<39]
test:
  requires:
    - pandas
    - pip
    - python
    - setuptools
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.extra.pandas
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.internal.conjecture.shrinking
    - hypothesis.strategies
    - hypothesis.strategies._internal
    - hypothesis.utils
    - hypothesis.vendor
  commands:
    - pip check
    - hypothesis --help

about:
  home: https://hypothesis.works/
  license: MPL-2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: A library for property based testing
  description: |
      Hypothesis is an advanced testing library for Python. It lets you write
      tests which are parametrized by a source of examples, and then generates
      simple and comprehensible examples that make your tests fail. This lets
      you find more bugs in your code with less work.
  dev_url: https://github.com/HypothesisWorks/hypothesis-python
  doc_url: https://hypothesis.readthedocs.io/en/latest

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
