{% set version = "3.81.0" %}


package:
  name: hypothesis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hypothesis/hypothesis-{{ version }}.tar.gz
  sha256: ee62108792c928187ba52a962215e65d4852025b190015940b006a02e26de17c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - attrs >=16.0.0
    - enum34  # [py<34]

test:
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.strategies
    - hypothesis.stateful

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  license_file: LICENSE.txt
  summary: 'A library for property based testing'

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
