{% set name = "hypothesis" %}
{% set version = "6.138.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 82e3b2ac709ee3edda4aba2f4b11becfe764f51d104fcdb3e9f95aff1ac81595

    # tests and tests data files
  - url: https://github.com/HypothesisWorks/{{ name }}/archive/refs/tags/{{ name }}-python-{{ version }}.zip
    sha256: af1c6b4b705de599718472436ab2cb4303296523e22301b02376474ad892c2b6
    folder: gh_src

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - hypothesis = hypothesis.extra.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools >=78.1.0
  run:
    - python
    - attrs >=22.2.0
    - exceptiongroup >=1.0.0  # [py<311]
    - sortedcontainers >=2.1.0,<3.0.0
  run_constrained:
      #-- cli tool
    - click >=7.0,!=8.2.2 # 8.2.2 was yanked
    - black >=20.8b0
    - rich >=9.0.0
      #--
    - libcst >=0.3.16
    - pytz >=2014.1
    - python-dateutil >=1.4
    - lark >=0.10.1
    - numpy >=1.19.3
    - pandas >=1.1
    - pytest >=4.6
    - dpcontracts >=0.4
    - redis-py >=3.0.0
    - hypothesis-crosshair >=0.0.24
    - crosshair-tool >=0.0.93
    - python-tzdata >=2025.2  # [win]
    - django >=4.2
    - watchdog >=4.0.0

# Skipping tests due to IndexError: -1
# test_database_directory_inaccessible:
# test_database_backend.py::test_database_directory_inaccessible[dirs0] - Failed:
# DID NOT WARN. No warnings of type (<class 'hypothesis.errors.HypothesisWarning'>,) were emitted.
{% set skip_broken_tests = [
    "test_observability",
    "test_capture_unnamed_arguments",
    "test_failure_includes_explain_phase_comments",
    "test_failure_includes_notes",
    "test_normal_representation_includes_draws",
    "test_capture_named_arguments",
    "test_assume_has_status_reason",
    "test_minimal_failing_observation",
    "test_all_failing_observations_have_reproduction_decorator",
    "test_observability_captures_stateful_reprs",
    "test_metadata_to_json",
    "test_database_directory_inaccessible",
    "test_can_run_with_no_db",
    "TestMachineWithConsumingRule"
] %}

test:
  source_files:
    - gh_src/hypothesis-python
  requires:
    - pandas  # [not py>312] break circular dependency numpy -> hypothesis -> pandas -> numpy
    - pip
    - pytest
    - pytest-xdist
    - pexpect
      #-- cli tool
    - click >=7.0,!=8.2.2 # 8.2.2 was yanked
    - black >=20.8b0
    - rich >=9.0.0
      #--
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.extra.pandas  # [not py>312] break circular dependency numpy -> hypothesis -> pandas -> numpy
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.internal.conjecture.shrinking
    - hypothesis.strategies
    - hypothesis.strategies._internal
    - hypothesis.utils
    - hypothesis.vendor
    - hypothesis._settings
    - hypothesis.configuration
    - hypothesis.control
    - hypothesis.core
    - hypothesis.database
    - hypothesis.entry_points
    - hypothesis.errors
    - hypothesis.provisional
    - hypothesis.reporting
    - hypothesis.stateful
    - hypothesis.statistics
    - hypothesis.version

  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - hypothesis --help
    - pytest -o pythonpath=gh_src/hypothesis-python gh_src/hypothesis-python/tests/cover -vv --color=yes -n auto --dist=loadscope --maxfail=1 --durations=25 -k "not ({{ skip_broken_tests | join(' or ') }})"

about:
  home: https://hypothesis.works
  license: MPL-2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: A library for property based testing
  description: |
    Hypothesis is an advanced testing library for Python. It lets you write
    tests which are parametrized by a source of examples, and then generates
    simple and comprehensible examples that make your tests fail. This lets
    you find more bugs in your code with less work.
  dev_url: https://github.com/hypothesisWorks/hypothesis
  doc_url: https://hypothesis.readthedocs.io

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
