{% set version = "4.43.9" %}

package:
  name: hypothesis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hypothesis/hypothesis-{{ version }}.tar.gz
  sha256: be1a4e9916d30de3f6d9e1a81824b5668ed053fe77609734b95045a0f51d3e03

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - attrs >=19.2.0
    - enum34  # [py<34]

test:
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.strategies
    - hypothesis.stateful

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  license_file: LICENSE.txt
  summary: 'A library for property based testing'

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
