{% set name = "hypothesis" %}
{% set version = "6.140.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: b3b4a162134eeef8a992621de6c43d80e03d44704a3c3bfb5b9d0661b375b0d2

    # tests and tests data files
  - url: https://github.com/HypothesisWorks/{{ name }}/archive/refs/tags/{{ name }}-python-{{ version }}.tar.gz
    sha256: 71ca1e59648b1b4841fe027d0727dac387b5189e73fd1f23f6635fe263401786
    folder: gh_src

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - hypothesis = hypothesis.extra.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools >=78.1.0
  run:
    - python
    - attrs >=22.2.0
    - exceptiongroup >=1.0.0  # [py<311]
    - sortedcontainers >=2.1.0,<3.0.0
  run_constrained:
    # cli
    - click >=7.0,!=8.2.2 # 8.2.2 was yanked
    - rich >=9.0.0
    # ghostwriter
    - black >=20.8b0
    # codemods
    - libcst >=0.3.16
    # pytz
    - pytz >=2014.1
    # dateutil
    - python-dateutil >=1.4
    # lark
    - lark >=0.10.1
    # numpy
    - numpy >=1.19.3
    # pandas
    - pandas >=1.1
    # dpcontracts
    - dpcontracts >=0.4
    # redis
    - redis-py >=3.0.0
    # crosshair
    - hypothesis-crosshair >=0.0.25
    - crosshair-tool >=0.0.95
    # zoneinfo
    - python-tzdata >=2025.2  # [win]
    # django
    - django >=4.2
    # watchdog
    - watchdog >=4.0.0

test:
  source_files:
    - gh_src/hypothesis-python
  requires:
    - pandas
    - pip
    - pytest >=4.6
    - pytest-xdist
    - pexpect
    - click >=7.0,!=8.2.2 # 8.2.2 was yanked
    - black >=20.8b0
    - rich >=9.0.0
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.extra.pandas
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.internal.conjecture.shrinking
    - hypothesis.strategies
    - hypothesis.strategies._internal
    - hypothesis.utils
    - hypothesis.vendor
    - hypothesis._settings
    - hypothesis.configuration
    - hypothesis.control
    - hypothesis.core
    - hypothesis.database
    - hypothesis.entry_points
    - hypothesis.errors
    - hypothesis.provisional
    - hypothesis.reporting
    - hypothesis.stateful
    - hypothesis.statistics
    - hypothesis.version
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - hypothesis --help
    - pytest -o pythonpath=gh_src/hypothesis-python gh_src/hypothesis-python/tests/cover -vv --color=yes -n auto --dist=loadscope --maxfail=1 --durations=25

about:
  home: https://hypothesis.works
  license: MPL-2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: A library for property based testing
  description: |
    Hypothesis is an advanced testing library for Python. It lets you write
    tests which are parametrized by a source of examples, and then generates
    simple and comprehensible examples that make your tests fail. This lets
    you find more bugs in your code with less work.
  dev_url: https://github.com/hypothesisWorks/hypothesis
  doc_url: https://hypothesis.readthedocs.io

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu