{% set version = "6.0.2" %}

package:
  name: hypothesis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hypothesis/hypothesis-{{ version }}.tar.gz
  sha256: ae616551c8ebe897454e2de5183e325f6a109f70d45b7380154ed974ce8d4772

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - attrs >=19.2.0
    - sortedcontainers >=2.1.0,<3.0.0

test:
  requires:
    - django
    - pandas
    - setuptools 
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.extra.django
    - hypothesis.extra.pandas
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.internal.conjecture.shrinking
    - hypothesis.strategies
    - hypothesis.strategies._internal
    - hypothesis.utils
    - hypothesis.vendor

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: 'A library for property based testing'
  description: |
      Hypothesis is an advanced testing library for Python. It lets you write
      tests which are parametrized by a source of examples, and then generates
      simple and comprehensible examples that make your tests fail. This lets
      you find more bugs in your code with less work.
  dev_url: https://github.com/HypothesisWorks/hypothesis-python
  doc_url: https://hypothesis.readthedocs.io/

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
