{% set pkgname = "hypothesis" %}
{% set version = "3.21.1" %}
{% set sha256 = "aad9779a18c00536f84776e6d32602bb4ecd3ebc2469730fa974fb0a50028056" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - enum34  # [py<34]

test:
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.searchstrategy
    - hypothesis.tools
    - hypothesis.utils
    - hypothesis.vendor

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  summary: 'A library for property based testing'

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
