{% set version = "5.8.5" %}

package:
  name: hypothesis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hypothesis/hypothesis-{{ version }}.tar.gz
  sha256: 784ef70aecfe1d2c7dfa7c1027b1fcca362c2a4c8269d341d9ad3b5757c20d17

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - attrs >=19.2.0
    - sortedcontainers >=2.1.0,<3.0.0

test:
  requires:
    - django
    - pandas
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.extra.django
    - hypothesis.extra.pandas
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.internal.conjecture.shrinking
    - hypothesis.strategies
    - hypothesis.strategies._internal
    - hypothesis.utils
    - hypothesis.vendor

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  license_file: LICENSE.txt
  summary: A library for property based testing

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
