{% set version = "4.18.3" %}

package:
  name: hypothesis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hypothesis/hypothesis-{{ version }}.tar.gz
  sha256: 61d181d49eef601cc3c2bbd91acc8d40f3793153b90f12e165a45ae931b76528

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - attrs >=16.0.0
    - enum34  # [py<34]

test:
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.strategies
    - hypothesis.stateful

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: 'A library for property based testing'
  description: |
      Hypothesis is an advanced testing library for Python. It lets you write
      tests which are parametrized by a source of examples, and then generates
      simple and comprehensible examples that make your tests fail. This lets
      you find more bugs in your code with less work.
  dev_url: https://github.com/HypothesisWorks/hypothesis-python
  doc_url: https://hypothesis.readthedocs.io/

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
