{% set name = "hypothesis" %}
{% set version = "6.142.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/HypothesisWorks/{{ name }}/archive/refs/tags/{{ name }}-python-{{ version }}.tar.gz
  sha256: cc4166fbefeb10ee750d5f9397276880c6cb6877183d23d7e0fb1af88c9ee0c5

build:
  number: 1
  script: {{ PYTHON }} -m pip install ./hypothesis-python --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - hypothesis = hypothesis.extra.cli:main
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=78.1.0
  run:
    - python
    - attrs >=22.2.0
    - exceptiongroup >=1.0.0  # [py<311]
    - sortedcontainers >=2.1.0,<3.0.0
  run_constrained:
    # cli
    - click >=7.0,!=8.2.2 # 8.2.2 was yanked
    - rich >=9.0.0
    # codemods
    - libcst >=0.3.16
    # ghostwriter
    - black >=20.8b0
    # pytz
    - pytz >=2014.1
    # dateutil
    - python-dateutil >=1.4
    # lark
    - lark >=0.10.1
    # numpy
    - numpy >=1.21.6
    # pandas
    - pandas >=1.1
    # dpcontracts
    - dpcontracts >=0.4
    # redis
    - redis-py >=3.0.0
    # crosshair
    - hypothesis-crosshair >=0.0.25
    - crosshair-tool >=0.0.97
    # zoneinfo
    - python-tzdata >=2025.2  # [win]
    # django
    - django >=4.2
    # watchdog
    - watchdog >=4.0.0

# > raise UnsatisfiedAssumption(f"failed to satisfy {where}")
# E hypothesis.errors.UnsatisfiedAssumption: failed to satisfy assume() in do_it_all (line 80)
{% set skip_tests = "test_observability" %}
test:
  source_files:
    - hypothesis-python/tests
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.extra.pandas
    - hypothesis.internal
    - hypothesis.internal.conjecture
    - hypothesis.internal.conjecture.shrinking
    - hypothesis.strategies
    - hypothesis.strategies._internal
    - hypothesis.utils
    - hypothesis.vendor
    - hypothesis._settings
    - hypothesis.configuration
    - hypothesis.control
    - hypothesis.core
    - hypothesis.database
    - hypothesis.entry_points
    - hypothesis.errors
    - hypothesis.provisional
    - hypothesis.reporting
    - hypothesis.stateful
    - hypothesis.statistics
    - hypothesis.version
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - hypothesis --help
    # Skip testing on python 3.14 once pandas will be rebuilt
    - python -m pytest -v hypothesis-python/tests/cover -vv --color=yes -n auto --dist=loadscope --maxfail=1 --durations=25 -k "not ({{ skip_tests }})" # [py314]
  requires:
    - pandas # [py<314]
    - pip
    - pytest >=4.6
    - pytest-xdist
    - pexpect
    - click >=7.0,!=8.2.2 # 8.2.2 was yanked
    - rich >=9.0.0

about:
  home: https://hypothesis.works
  license: MPL-2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: A library for property based testing
  description: |
    Hypothesis is an advanced testing library for Python. It lets you write
    tests which are parametrized by a source of examples, and then generates
    simple and comprehensible examples that make your tests fail. This lets
    you find more bugs in your code with less work.
  dev_url: https://github.com/hypothesisWorks/hypothesis
  doc_url: https://hypothesis.readthedocs.io

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu