{% set pkgname = "hypothesis" %}
{% set version = "3.49.1" %}
{% set sha256 = "659543b346f02dd0437541e0b033574e91d674aa6a9ed32555399c3ed48f4c1e" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - attrs
    - coverage
    - enum34  # [py<34]

{% set pytestcmd = "python -m pytest " %}  
{% set pytestcmd = "python -m pytest -n 0 " %}  # [py35]

test:
  requires:
    - pytest-xdist
    - numpy
    - pandas
    - pytz
    - faker
    - mock
    - flaky
    - ipaddress  # [py2k]
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.strategies
    - hypothesis.stateful
  commands:
    - git clone https://github.com/HypothesisWorks/hypothesis-python.git src
    - cd src
    - {{ pytestcmd }} tests/cover
    - {{ pytestcmd }} tests/datetime
    - {{ pytestcmd }} tests/fakefactory
    - {{ pytestcmd }} tests/numpy
    - {{ pytestcmd }} tests/pandas
    - {{ pytestcmd }} tests/py2  # [py2k]
    - {{ pytestcmd }} tests/py3  # [py3k]
    - {{ pytestcmd }} tests/pytest -p pytester --runpytest subprocess

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  summary: 'A library for property based testing'

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
