{% set version = "3.88.2" %}


package:
  name: hypothesis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hypothesis/hypothesis-{{ version }}.tar.gz
  sha256: 14550e1620e5afd6007680c7456d6f5e44986010efb69d1ccef5a4f5fd6ae80a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - attrs >=16.0.0
    - enum34  # [py<34]

test:
  imports:
    - hypothesis
    - hypothesis.extra
    - hypothesis.strategies
    - hypothesis.stateful

about:
  home: https://github.com/HypothesisWorks/hypothesis-python
  license: MPL 2.0
  license_file: LICENSE.txt
  summary: 'A library for property based testing'

extra:
  recipe-maintainers:
    - ericmjl
    - jochym
    - tadeu
